<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-1GQ8CG3" failures="2" tests="3" name="Test" time="26.032" errors="0" timestamp="2025-07-15T23:56:02 IST">
  <testcase classname="day4.tests.Start" name="testScript1" time="9.353"/>
  <testcase classname="day4.tests.Start" name="testScript2" time="5.306">
    <failure type="java.lang.AssertionError" message="Login failed! expected [https://www.saucedemo.com/v1/inventory.html] but found [https://www.saucedemo.com/v1/]">
      <![CDATA[java.lang.AssertionError: Login failed! expected [https://www.saucedemo.com/v1/inventory.html] but found [https://www.saucedemo.com/v1/]
at day4.tests.Start.testScript2(Start.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testScript2 -->
  <testcase classname="day4.tests.Start" name="testScript3" time="5.265">
    <failure type="java.lang.AssertionError" message="Login failed! expected [https://www.saucedemo.com/v1/inventory.html] but found [https://www.saucedemo.com/v1/]">
      <![CDATA[java.lang.AssertionError: Login failed! expected [https://www.saucedemo.com/v1/inventory.html] but found [https://www.saucedemo.com/v1/]
at day4.tests.Start.testScript3(Start.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testScript3 -->
</testsuite> <!-- Test -->
